from pages.base_page import BasePage
from pages.launch_page  import LaunchPage,LaunchPageIOS
from pages.login_page import LoginPage,LoginPageIOS
from pages.home_page import HomePage,HomePageIOS
from pages.roaming_page import RoamingPage,RoamingPageIOS
from pages.boost_page import BoostPage,BoostPageIOS
from pages.feedback_page import FeedbackPage,FeedbackPageIOS
from pages.password_page import PasswordPage,PasswordIOS
from pages.profile_page import ProfilePage,ProfilePageIOS
from pages.payment_page import PaymentPage,PaymentPageIOS